### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by akalankapagoda** [ballerina-lang/tools-distribution#43]
When running ballerina in a previous version of JDK than JDK 1.8, the following error occurs and the programs exits.

```
ballerina-tools-0.8.0/bin$ ./ballerina run ../samples/helloWorld/helloWorld.bal
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/ballerinalang/launcher/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

**Comment by hjchanna** [comment]
In windows operating system it stops working without any error message. Ballerina requires jdk 1.8 (or may be above) to run (ballerina core contains lambda functions which requires jdk1.8). It may need to show an error message to clearly let to know "there is a java version incompatibility issue".

**Comment by uthaiyashankar** [comment]
This should have been fixed in the latest versions.
